app/__init__.py
from flask import Flask
from .database.base import db
from flask_migrate import Migrate
from flask_wtf.csrf import CSRFProtect
from flask_login import LoginManager
from app.modules.user.user_model import User
from .errors import make_handler
from .config import Config
from .modules.public_pages.public_pages_blueprint import public_pages_blueprint
from .modules.user.user_blueprint import user_blueprint
from .modules.auth.auth_blueprint import auth_blueprint
from .modules.forgot_password.forgot_password_blueprint import (
    forgot_password_blueprint,
)
from .modules.dashboard.dashboard_blueprint import dashboard_blueprint


"""
instantiation of main application and crucial plugins
"""
app = Flask(__name__)
app.config.from_object(Config)
csrf = CSRFProtect(app)
db.init_app(app)
migrate = Migrate(app, db)


"""
login manager configuration
"""
login_manager = LoginManager()
login_manager.init_app(app)
login_manager.user_loader(lambda user_id: User.query.get(int(user_id)))


"""
global error handlers 
"""
app.register_error_handler(401, make_handler(401, "Unauthorized"))
app.register_error_handler(404, make_handler(404, "Page not found"))
app.register_error_handler(500, make_handler(500, "Internal server error"))


"""
    register all blueprints (i.e. sub-routers) here
"""
app.register_blueprint(public_pages_blueprint)
app.register_blueprint(user_blueprint, url_prefix="/user")
app.register_blueprint(auth_blueprint, url_prefix="/auth")
app.register_blueprint(forgot_password_blueprint, url_prefix="/forgot-password")
app.register_blueprint(dashboard_blueprint, url_prefix="/dashboard")

app/modules/dashboard/dashboard_blueprint.py
from flask import Blueprint, render_template
from flask_login import login_required

dashboard_blueprint = Blueprint("dashboard", __name__, template_folder="templates")


@dashboard_blueprint.get("/")
@login_required
def dashboard_page():
    return render_template("dashboard.html")

app/modules/forgot_password/forgot_password_blueprint.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .forgot_password_forms import ForgotPasswordForm, ResetPasswordForm
from flask_login import current_user
from .forgot_password_service import (
    process_forgot_password,
    reset_user_password,
)
from app.utilities.jwt import validate_password_reset_token


forgot_password_blueprint = Blueprint(
    "forgot_password", __name__, template_folder="templates"
)


@forgot_password_blueprint.route("/", methods=["GET", "POST"])
def forgot_password():
    if current_user.is_authenticated:
        flash(
            "You are already logged-in. If you need to update your account password please go to your account settings.",
            "info",
        )
        return redirect(url_for("public_pages.home_page"))

    form = ForgotPasswordForm(request.form)
    if form.validate_on_submit():
        token = process_forgot_password(form.email.data)
        if token:
            flash("You request will be processed: " + token, "info")

    return render_template("forgot_password.html", form=form)


@forgot_password_blueprint.route("/reset/<token>", methods=["GET", "POST"])
def reset_password(token: str):
    user_id = validate_password_reset_token(token)
    if not user_id:
        if request.method == "GET":
            return render_template(
                "errors/error.html",
                status=400,
                message="Invalid or expired link",
            )

    form = ResetPasswordForm(request.form)
    if form.validate_on_submit():
        reset_user_password(user_id, form.password.data)
        flash("Account password updated successfully", "success")
        return redirect(url_for("public_pages.home_page"))

    return render_template("reset_password.html", form=form, token=token)

app/modules/public_pages/public_pages_blueprint.py
from flask import Blueprint, render_template

public_pages_blueprint = Blueprint(
    "public_pages", __name__, template_folder="templates"
)


@public_pages_blueprint.get("/")
def home_page():
    message = "Hello from home page"
    return render_template("home.html", message=message)

app/modules/user/user_blueprint.py
from flask import Blueprint, render_template, flash, redirect, url_for, request
from .user_service import register_user
from .user_forms import UserRegisterForm
from flask_login import current_user

user_blueprint = Blueprint("user", __name__, template_folder="templates")


@user_blueprint.route("/register", methods=["GET", "POST"])
def user_register():
    if current_user.is_authenticated:
        flash("You are already logged-in", "info")
        return redirect(url_for("public_pages.home_page"))

    form = UserRegisterForm(request.form)
    if form.validate_on_submit():
        new_user = register_user(form.email.data, form.password.data)
        if not new_user:
            return render_template("auth.login")

        flash("Account created successfully", "success")
        return redirect(url_for("auth.login"))

    return render_template("user_register.html", form=form)

app/templates/layouts/base_layout.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link rel="stylesheet" href="{{ url_for('static', filename='dist/global.css') }}" />
  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.png') }}" type="image/png" />
  {% block scripts %}{% endblock %}
  <title>Site - {% block title %}{% endblock %}</title>
</head>

<body>
  {% block body %}{% endblock %}
</body>

</html>

app/templates/layouts/dashboard_layout.html
{% extends "layouts/base_layout.html" %}
{% block body %}
<div class="container mx-auto px-4">
  <div class="grid grid-cols-4 grid-rows-2">
    <div class="col-span-4 py-4">
      <div class="flex justify-between">
        <div>
          <a href="{{ url_for('dashboard.dashboard_page') }}">
            <img src="{{ url_for('static', filename='logo.png') }}" alt="logo" class="h-10" />
          </a>
        </div>

        <div class="flex space-x-2">
          <a href="{{ url_for('auth.user_logout') }}"
            class="text-sm my-auto text-gray-800 hover:bg-gray-100 px-3 py-2 rounded">Logout</a>
        </div>
      </div>
    </div>

    <div class="col-span-1 pt-4 flex-col">
      <a href="/dashboard/profile" class="block hover:bg-gray-100 w-full p-2">Profile</a>
    </div>

    <div class="col-span-3 px-4">
      <main>
        {% include "segments/flash.html" %}{% block content %}{% endblock %}
      </main>
    </div>
  </div>
</div>
{% endblock %}

app/templates/layouts/public_layout.html
{% extends "layouts/base_layout.html" %}
{% block body %}
<div class="container mx-auto">{% include "segments/navbar.html" %}</div>
<div class="container mx-auto px-4">{% include "segments/flash.html" %}</div>
<main class="container mx-auto px-4">{% block content %}{% endblock %}</main>
{% endblock %}

app/templates/macros/field_errors.html
{% macro field_errors(field) %}
{% if field.errors %}
<ul class="py-1">
  {% for error in field.errors %}
  <li class="text-sm text-red-800">{{ error }}</li>
  {% endfor %}
</ul>
{% endif %}
{% endmacro %}

app/templates/macros/message.html
{% macro message(text) %}
<div class="bg-blue-200 rounded p-3">
    <p class="text-sm text-blue-900">{{ text }}</p>
</div>
{% endmacro %}

app/templates/segments/flash.html
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
<aside>
  {% for category, message in messages %}
  <ul class="flash-{{ category }} px-3 py-2 rounded">
    <li class="text-sm py-2">{{ message }}</li>
  </ul>
  {% endfor %}
</aside>
{% endif %}
{% endwith %}

app/templates/segments/navbar.html
<nav class="flex justify-between p-4">
  <div>
    <a href="{{ url_for('public_pages.home_page') }}">
      <img src="{{ url_for('static', filename='logo.png') }}" alt="logo" class="h-10" />
    </a>
  </div>

  <div class="flex space-x-2">
    {% if current_user.is_authenticated %}
    <a href="{{ url_for('dashboard.dashboard_page') }}"
      class="text-sm my-auto text-gray-800 hover:bg-gray-100 px-3 py-2 rounded">Dashboard</a>
    {% endif %}

    {% if current_user.is_anonymous %}
    <a href="{{ url_for('user.user_register') }}"
      class="text-sm my-auto text-gray-800 hover:bg-gray-100 px-3 py-2 rounded">Register</a>
    <a href="{{ url_for('auth.login') }}"
      class="text-sm my-auto text-gray-800 hover:bg-gray-100 px-3 py-2 rounded">Login</a>
    {% endif %}

    {% if current_user.is_authenticated %}
    <a href="{{ url_for('auth.user_logout') }}"
      class="text-sm my-auto text-gray-800 hover:bg-gray-100 px-3 py-2 rounded">Logout</a>
    {% endif %}
  </div>
</nav>