app/modules/forgot_password/forgot_password_blueprint.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .forgot_password_forms import ForgotPasswordForm, ResetPasswordForm
from flask_login import current_user
from .forgot_password_service import (
    process_forgot_password,
    reset_user_password,
)
from app.utilities.jwt import validate_password_reset_token


forgot_password_blueprint = Blueprint(
    "forgot_password", __name__, template_folder="templates"
)


@forgot_password_blueprint.route("/", methods=["GET", "POST"])
def forgot_password():
    if current_user.is_authenticated:
        flash(
            "You are already logged-in. If you need to update your account password please go to your account settings.",
            "info",
        )
        return redirect(url_for("public_pages.home_page"))

    form = ForgotPasswordForm(request.form)
    if form.validate_on_submit():
        token = process_forgot_password(form.email.data)
        if token:
            flash("You request will be processed: " + token, "info")

    return render_template("forgot_password.html", form=form)


@forgot_password_blueprint.route("/reset/<token>", methods=["GET", "POST"])
def reset_password(token: str):
    user_id = validate_password_reset_token(token)
    if not user_id:
        if request.method == "GET":
            return render_template(
                "errors/error.html",
                status=400,
                message="Invalid or expired link",
            )

    form = ResetPasswordForm(request.form)
    if form.validate_on_submit():
        reset_user_password(user_id, form.password.data)
        flash("Account password updated successfully", "success")
        return redirect(url_for("public_pages.home_page"))

    return render_template("reset_password.html", form=form, token=token)

app/modules/forgot_password/templates/forgot_password.html
{% extends "layouts/public_layout.html" %}
{% block title %}Reset Password{% endblock %}
{% from "macros/field_errors.html" import field_errors %}
{% from "macros/message.html" import message %}
{% block content %}
<div class="py-6">
  <h2 class="text-xl text-gray-800 mb-4">Reset password</h2>

  {{ message("Please enter your account email address. If the provided email address is valid you will receive
  an email with instruction for resetting your account password.") }}

  <form action="{{ url_for('forgot_password.forgot_password') }}" method="post" class="flex-col space-y-8">
    {{ form.csrf_token }}
    <fieldset class="flex-col space-y-2">
      <label for="email" class="block text-sm text-gray-800">Email</label>
      <input type="email" id="email" name="email" class="bg-gray-200 px-3 py-2 rounded active:bg-gray-300 w-full"
        required {% if form.email.data %} value="{{ form.email.data }}" {% endif %} autocomplete="email" />
      {{ field_errors(form.email) }}
    </fieldset>

    <fieldset>
      <input type="submit" value="Submit" class="text-sm text-white bg-blue-600 px-4 py-2 rounded" />
    </fieldset>
  </form>
</div>
{% endblock %}

app/modules/forgot_password/templates/reset_password.html
{% extends "layouts/public_layout.html" %}
{% block title %}Set new password{% endblock %}
{% from "macros/field_errors.html" import field_errors %}
{% block content %}
<div class="py-6">
  <h2 class="text-xl text-gray-800 mb-4">Set new password</h2>
  <form action="{{ url_for('forgot_password.reset_password', token=token) }}" method="post" class="flex-col space-y-8">
    {{ form.csrf_token }}
    <fieldset>
      <label for="password" class="block text-sm text-gray-800">Password</label>
      <input type="password" name="password" class="bg-gray-200 px-3 py-2 rounded active:bg-gray-300 w-full" required
        minlength="8" />
      {{ field_errors(form.password) }}
    </fieldset>

    <fieldset>
      <label for="confirm_password" class="block text-sm text-gray-800">Confirm Password</label>
      <input type="password" name="confirm_password" class="bg-gray-200 px-3 py-2 rounded active:bg-gray-300 w-full"
        required minlength="8" />
      {{ field_errors(form.confirm_password) }}
    </fieldset>

    <fieldset>
      <input type="submit" value="Submit" class="text-sm text-white bg-blue-600 px-4 py-2 rounded" />
    </fieldset>
  </form>
</div>
{% endblock %}